apiVersion: v1
kind: Service
metadata:
  name: {{ include "factory-monitor.fullname" . }}-api
  labels:
    {{- include "factory-monitor.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    app: {{ include "factory-monitor.fullname" . }}-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
