apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-worker
  labels:
    {{- include "factory-monitor.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingest-worker
spec:
  replicas: {{ .Values.ingestWorker.replicas }}
  selector:
    matchLabels:
      app: ingest-worker
  template:
    metadata:
      labels:
        app: ingest-worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
        prometheus.io/path: "/metrics"
    spec:
      initContainers:
        {{- include "factory-monitor.waitForDb" . | nindent 8 }}
      containers:
        - name: ingest-worker
          image: "{{ .Values.ingestWorker.image.repository }}:{{ .Values.ingestWorker.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9101
          envFrom:
            - configMapRef:
                name: {{ include "factory-monitor.fullname" . }}-app
            - secretRef:
                name: {{ include "factory-monitor.fullname" . }}-app
          readinessProbe:
            tcpSocket:
              port: 9101
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          resources:
            {{- toYaml .Values.ingestWorker.resources | nindent 12 }}
