apiVersion: v1
kind: Service
metadata:
  name: ingest-worker
  labels:
    {{- include "factory-monitor.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingest-worker
spec:
  clusterIP: None
  selector:
    app: ingest-worker
  ports:
    - name: metrics
      port: 9101
      targetPort: 9101
