apiVersion: v1
kind: Service
metadata:
  name: notifier-worker
  labels:
    {{- include "factory-monitor.labels" . | nindent 4 }}
    app.kubernetes.io/component: notifier-worker
spec:
  clusterIP: None
  selector:
    app: notifier-worker
  ports:
    - name: metrics
      port: 9103
      targetPort: 9103
