apiVersion: v1
kind: Secret
metadata:
  name: {{ include "factory-monitor.fullname" . }}-app
  labels:
    {{- include "factory-monitor.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://factory:factory@postgres:5432/factory"
  ALEMBIC_DATABASE_URL: "postgresql://factory:factory@postgres:5432/factory"
  POSTGRES_PASSWORD: "factory"
